### ISSUE TITLE
How about you put this on GitHub pages

### ISSUE THREAD

**Issue by IAmMaulik** [codeSTACKr/free-developer-resources#8]
It would be nice if you put this repository on github pages and then people will have a website to go to instead of a github repo. The README will become the front-end of the website

**Comment by codeSTACKr** [comment]
That's a great idea! I'm going to take a look at doing that. Any easy ways to render the README that you know of?

**Comment by Karthik-Nayak98** [comment]
Why can have a card layout kind of thing? We can write a Github action to update that website

**Comment by IAmMaulik** [comment]
@codeSTACKr  No you don't need to do anything to render the README as the frontend. You just have to activate GitHub pages and it just happens on it's own

**Comment by codeSTACKr** [comment]
Cool, done! 
https://codestackr.github.io/free-developer-resources/
